const mongoose = require('mongoose');

const bookingSchema = new mongoose.Schema({
  hotelId: { type: mongoose.Schema.Types.ObjectId, ref: 'Hotel', required: true },
  roomId: { type: mongoose.Schema.Types.ObjectId, ref: 'Room', required: true },
  guestName: { type: String, required: true },
  guestContact: { type: String, required: true },
  checkInDate: { type: Date, required: true },
  checkOutDate: { type: Date, required: true },
  totalAmount: { type: Number, required: true },
  status: { 
    type: String, 
    enum: ['pending', 'confirmed', 'checked-in', 'checked-out', 'cancelled'],
    default: 'confirmed'
  },
  paymentStatus: {
    type: String,
    enum: ['pending', 'paid', 'partial'],
    default: 'pending'
  },
  paymentMode: { type: String, enum: ['Prepaid', 'Pay At Hotel', 'Bill To Company'], default: 'Prepaid' },
  paymentMethod: { type: String, default: 'Cash' },
  paymentReference: { type: String },
  internalNotes: { type: String },
  paidAmount: { type: Number, default: 0 },
  pendingAmount: { type: Number, default: 0 },
  bookingGroupId: { type: String },
  adults: { type: Number, default: 2 },
  children: { type: Number, default: 0 },
  infant: { type: Number, default: 0 },
  mealPlan: { type: String, default: 'Room Only' },
  cost: { type: Number, default: 0 },
  gst: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  discountType: { type: String, enum: ['flat', 'percent'], default: 'flat' },
  discountValue: { type: Number, default: 0 },
  gstMode: { type: String, enum: ['inclusive', 'exclusive', 'out_of_scope'], default: 'exclusive' },
  guestEmail: { type: String },
  guestAddress: { type: String },
  guestDob: { type: Date },
  gender: { type: String },
  guestCountry: { type: String, default: 'India' },
  guestState: { type: String },
  guestCity: { type: String },
  companyName: { type: String },
  companyGst: { type: String },
  companyAddress: { type: String },
  idProofType: { type: String },
  idProofNumber: { type: String },
  comingFrom: { type: String },
  goingTo: { type: String },
  vehicleNumber: { type: String },
  nameAsPerIdProof: { type: String },
  nationality: { type: String, default: 'Indian' },
  arrivalTime: { type: String },
  specialRequests: { type: String },
  haveGst: { type: String, enum: ['Yes', 'No'], default: 'No' },
  onDutyManager: { type: String },
  departureDateTime: { type: Date },
  checkoutComment: { type: String },
  markRoomTo: { type: String, default: 'Dirty' },
  emailInvoiceToGuest: { type: String, enum: ['Yes', 'No'], default: 'No' }
}, { timestamps: true });

module.exports = mongoose.model('Booking', bookingSchema);
